version: '3'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - tugas5

  wordpress:
    image: wordpress
    container_name: wordpress
    restart: always
    ports:
      - 3000:80
    volumes:
      - wordpress:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - mariadb
    networks:
      - tugas5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
    depends_on:
      - mariadb
    networks:
      - tugas5

  nginx:
    depends_on:
      - wordpress
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
    links:
      - wordpress
      - phpmyadmin
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - tugas5

volumes:
  db_data:
  wordpress:

networks:
  tugas5:
